---
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cluster-info.json: |
    {
      "cluster": {
        "name": "marcgitops"
      },
      "logs": {
        "region": "ap-northeast-1"
      }
    }
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
