---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUfaK6lREKMdXPBfm1QHHZ6Lled88wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI3MDkyMTAwWhcNMjQwODI1MDkyMTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALFzW3zDDsFSpn3+cp5gjWKGumYtrWABoDimIdiCpOkGtUOTKN/d+SU6jGJH6z65
    TqT21uGcmS832eVNwnwK52kIEeP30nYJF8e3sYzV9RDtVjsjiHYweY5/aUjOfNiz
    45pSlVXLGn04zcJSXK3H5TfH6JqgQo4q2QvZtRybV/Ziov1Z8ldE4oKGGYNyC3uL
    IB4d1MGRjr3b0/6qETvok83spXezLx1MqqERYpumFwc7pjvXpEzrj4xd1XtIL5Uk
    taU4AHjD8aDaZesw74DDjP7a73GngKYJ1x10QGQHIe+VbcqmA142rI2FeG3Wb2m7
    BM/WDhr/CfahqOCh9cCaXZ/gzVNlOt5arhV320X2/dzXSuBXIGtYr67tC3g/KbnX
    Hx7Ug9knfXvB4PAYQK07uqyIGd9pASnzm/TZ7oNjwZyX8b6SpMaI8NXxv+P2Tz5h
    ezMvaHY8VyF9HeP/5V7wqcgSHRMvSKKDEhgcDCcmqiBLXibomp2kSil9R8Vs5uMl
    /D+mlZOQFk5x0wEv+cw1Y7v52GkHbajeu3nnQHnTUg3qY12RIqws6aBY+zKiMdJo
    4Iw06lanH+vpvhYpCbiPK82tN8PsOI6YzrkJmkvlDVsnwuYCLXOwI7Q9RxrA4RbM
    BvQ+vMCWlS/FNTQTKpSwDvHkeOOSBF5LBQyrUGxRkmnxAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSb8BIOOIl8YNwh
    0EvBQ/1Shh2M9zANBgkqhkiG9w0BAQ0FAAOCAgEASmBjo+o8UTgKrhyrIwTkKI46
    AqRlFPf9ch79hBZnGKgijiqXMD6xWOWocMqVdOZrDgJ9BxPGdZ20vlB8G8XqRvJn
    Slkb2ELgxPz/FJMGZUwXiM8RfO78PjrR0a26Rk0BraFmvytVeetXGCA3yvhA+/h0
    9wqrRwX7d+9MquyW0jYbm55RT6g8+JapGhywuMbFRHFPoweqDFm5L4NNziJUJ2f0
    JDbYQfqRtWCnsXuH5dc+LbQfjLWN7W9fQzhBCtEBox+yMyvuR0CGBjD6VVsNAuUG
    9ecItAigFB9d5VoLreHT2dYTDxfc1QaKyDO2czy5NvEOoF5GYHm5sonNcQ1ryVec
    wMo3+1yNDqaXDL2eTtPV0TcMI0Q0eFxxvL41KJHhJN6zLy0lGAYN0ZtYKdat21tl
    yIAihMoY8K4OWNy8rGQjOZv34mIGyhYGHF/1PK74OswS/AIM6hWoGgnewAanLjbZ
    lFIlQ3MZv2mOyiaVkZBczvS9GJD2OJfe5mw4pYzXOJgMCuUWU9xoa3f8EnYj6adF
    RCp/MG315xYKDLhiZZgjsAWkT3EQbgXdHLW4Hhqpomf2LzpZbYt0Ms39cxRQr9d0
    iiTD+wgLhsDFtaDolstx/mtar67OR32GbMJo0B1Ao6FijOMaOKYc7xfAJVyKSJp3
    dQy51SJYPbe0jcDz8uA=
    -----END CERTIFICATE-----
    
