---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUXrLLTYKxO13Hayzk3auBvTUNY/gwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwOTA0MDk1OTAwWhcNMjQwOTAyMDk1OTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKcULl+CDtYQBP/wDmO2pQrTD4Cd4b2zSd9r1enQM+PoTijQ4r2GyWhPz48fi7MP
    DxepmaVB5Im/ZlVWu7eyp9xP22o+IKcOF4yIWSGn1DAWeCOIA2UazA6pntVt0CuX
    gHIVxCY3j+WTtQUBuwhJfJs5gJlM2w4jb7bzQyXe5tY2tzW3LdMbjMifxJq7uZ+r
    T/3esDqgTJOAngpf6F6vDQRjnvr83VU25NAlAxzhVVU3SPPrIZoQ3grjdrvcbbZp
    r0xfyCPxEWl0LKRia1ND+9P+/hnXDrFZbTQb4mv+Gh9HdM9L5xHWUm7i6C8AAyo7
    3dbU0uUdOkUBYBmIxHW3tt5xFl3oez0o7z24jbGyrfqcJy5khH+Bn/SkeBR1iCFJ
    TtbsCuDI6kIfsF1B1nxiXk9Vd8Zi6qp5kVdt85omct/KdsfHknVjwfL7xPoluNwo
    gB3i0vu8t2SpoRh4+baQAP2Ovs438mZ1BkWaIOR85oV0d0O4CrrqV5nnAI1IgGi2
    R888enXfp0Vrkb2qPepFyj+Af6YJSx/pAMw7FW+gvUzUc32hxavCzZPF1Yp94UHa
    CQC3iHm0aoRw8oBk7cX7XFd2JvJNP1/W5cAgv7Az8poRjgS+a+/8TJ/zIFbDj1fw
    EiIvxRWBFVsQoVRAHToEpsvcf168rurnOe9Mgf70RfwvAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQPLQobv4q2/tLX
    B7/HPTLi4LtTKjANBgkqhkiG9w0BAQ0FAAOCAgEAPA9JhKh5/djfQhMqT8zS06xf
    eQq5tpnMHFbMZrlWSxJM3BNw6vTwikIymJN5b+WjtLb0oq/Cptg/LRJoCoAVO216
    X/AbKR1Ujj9TYgBOp7e1cOBGRSvWYOHgKA9j59aXng8AvMExGassMSM/bsud5ikU
    J+CcDXbUUlyO5zk5L5WAhabePxwOHfC989NznJXgiGu2Tpjhf22Zei/recuMnadP
    0s3wvbEQL+dxEb1KCD86L/6lhiLG2lnMXCpZnTnEnLwona0/vmDHFmRuczsDvl+w
    0C4J7xDSXSGcQBNuAJs5LwXWeXelpTpZkpzdNtMjsVvEsj/XkOgBmFTTBo53km23
    QjtdmivLx/1/ZKrWeRR1RNzMQQ2LOvSw79NXwRARtxqcfABpAexBsSZTWYAc2b8F
    BYrs5yGQCiduWXIXiilaxHLWetKuaMWYhUfBWdyb8wrmo0cf662SxRyjkoUSDTfx
    7rzkl0SdtwOKMbNWD2iE9oK/jlXa5+jcFfAjYCqYB5TewOwqRdnCRl+mJf0Peg6b
    uzgBsfiHzWYFEX0s4BDPyachES/oUlqsMdrqixgXov8il0nFTN0uenKw+iKjSA4B
    ijuJuARUuTmbqj4FQZ3EhNRTKt/iXsJjzsIrIOguIEvPxEwE5sjmCkHBymOD9/EK
    YGiCYsoYNJQ/R1upgzI=
    -----END CERTIFICATE-----
    
