---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUUN+imwpHPx22kL/7LGpX2uOJqywwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI3MTAzMDAwWhcNMjQwODI1MTAzMDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AON8+hAh8CBIaAu/iCc1stRxEtz62SPTkFX+4WUK0S6iPyfIb1BqdCq77DCXz/xx
    5qPBrg0wC/UWQgvOKICckRHq+/k6yICePgwGxTLQMHlDg8wCo6DGz3y4LdRPypEA
    kytbKCdIyzVcqG0SherwZ1xFMtxviXwwEV+wPXc7Yf4rapHKtIH+hmYk3HwJdNBn
    6KYK4jBVrs35d5D82v9SWjlPHpp1t8QAMykCqiiOlNyB8MNtqsfwCg05lyqSOSso
    ftyz9/N0clfZgOD1gZCMMtCDXQGXTdhjSzzPI7n/FzGigGbTsA4iH65F6djCBvHQ
    XpWtlsaau4YtYDdHucfYkhjEAXi8HD+/VpYrh/tj9RMda5ruwnGUGwW+X6TaMUwV
    SFzW8dC1WpcgUrHeAleSxE0oxUW7PdTiCcx0rXEp7abUq/xhu6Pm0iAbjg6+nYQl
    4F1nFqzi7UI0+tjiK7RcoDANUU0dEpYEG13dMvZ/PMVfOz6EaUrUrupN3MP+dOQ6
    vM091DGDGBLXAs+aWq0T+Q0+sMgy8XNesgDNU19MZK4x+5AHyUI4UPy+Z1+8ImWb
    THou7V0ED1xKO3TWu7sqzlGdzdnmZi2Xx2PiAO0p1kWmIV1ldXMLxtGA3z4WukBR
    HEpFt9VTB59HzQDkJNhIz1a7saLZyI4oDy9KwMnAY1rhAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQa3AC22A2crvT8
    NQBSfaLunjEVxTANBgkqhkiG9w0BAQ0FAAOCAgEAxaWoe8RpmUCCsuBgnWWpcnQj
    r36XxK1vs58bxGouc4mEVqR7ckBw68+rLYgIXesrpelotRFtUmd2fzZnYuIxUfJU
    mzWuGafdd6owtDFdbjXUpm/l1la7yqwuUJNsEORPOxShyHCFZ6rsCwSOBzuVOPuC
    gPpQfOdpwBJR2ekpxrg/y1A/PLPeOm2piwfFJ1xATUsUc0FJ6o9ssok4z6jop+yB
    0tpfcPyYUFI+a0RMwfHXCgcQzD38KM0ESvthwBVyx4ZYe1T2I1er7fksTcbQIj0j
    LgNHGrgDGqO7sRnkHtRGm7jWwBwcRlG6zZEFAi7O0oG1hMNDi7YZgJFFc7+npFoK
    ttOb/hfWfGxm7oxEfg09TBKwee4Zvc9y8/fcrY12zYrqrUjzx3IvKciXvXtVknjv
    PXKQFTflRrRoxwwWVpYE+2MUmRkvJcuvsd5MVW0VLBtFpn5YPSNZObZ1XADho5ly
    qIwFHccMBsr/mR9TwmuTO2MkxkImPz54Oe/guOQ6KlYCovBqDgxWsT17on7eYSzZ
    dR+sCkjVwiwDHd4xAhQhFKLxwXV3osydOGf4U7eKORV4YNUgTw1KJLgMKpklTiKe
    yXaxiJnsFE+N58BxxoWJw86p02K/XJby4QgQgic4NNy0OGEhmujTvCY3c+idnrPG
    3iW66BatDrkfxJP8pRA=
    -----END CERTIFICATE-----
    
