---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUcm+04Vt0z2xLIomq5o8+ZdJk9nwwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwOTA1MTIyNjAwWhcNMjQwOTAzMTIyNjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANsE8YjL89//LkP16wT5EW7PyThvUvyAKcxRHJd+taWEd9qsuiSi1zVvUnShQUtF
    e0RdPDmDWtr5fxrIV7Uof7izU6LZjdItrfrlSV3C5eliuuqijp1z9vEh4iqpGwCD
    Jmr8a7pWuQlIJqXUpd3NtWG6a6Cp/LLFUM8mzG5s7c8GfrpUlK8jNerQ8G6d6wWc
    D+J6l4KA109PX4HM3ePGWruaYFeHbGWaBb+16QBwUv9HleouncxGXN1Xzd5hRPxo
    D0r7wFWVomf8o3NRtSaJxAdiG7sKo4/UuWimNktELhstn4cDcsAKqb8CuCdhIaIA
    BTyLZd3tWzFHuB3rKpKOcSxZnePGKP+Da2jPg5few7atWB8nKarhb7OLP3TPhqsJ
    2HQFBvTxHUJjEaWAiXn6U0G/N8WSLzaKR6GOjwWUendooe9VXvzyHbKMWlttQmdw
    96+WJ51NxBfO8zUB/8+F4U2p0M2tl7vCeZ43tynAVAw2sTbCOwtDOqBG3drAlAO3
    8jNPdRgDWQsoL7odygUdN32ES/w484eWsCSEFsZ9CD4wyAPfS+KpZDmUR9qN8BJv
    QRPb+soZsIaSD1F30539iARhEBpdVw308FuGn9BYFwiD6DY65nTCAy7o4F2aVbIh
    bFfFArPjq8y8ugwj6iy7uurTQbjOATik6S/xZ81L9cUrAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSV5W89THctSqgz
    plRXitDoPzGlsTANBgkqhkiG9w0BAQ0FAAOCAgEAWFtLiTrpR8H1LjBNdl81PHgZ
    BfYb2fE+CEJvk6f1UKirijfMR1RQ7ZYOpdSJr3jzniC0qT+wn/WIC6hzSCafOVoM
    yRS8YmPLJRFpchL2MmZs6xNGK8Ur28nF6MfhFAP0AG9hi2E5mG490LPapE5LUoKl
    sjmIFin4fvv28nmmdYG3KaW8sQ1oT21QKOYQTMFqFK27Wv1+LPJaShoRGC77olC1
    ooBAivxy/ZIhNewbZ1jX+VuNYAuqZuc5wacHnHrS9jGDyb+gPfv/OZkyu+8cl10g
    542X0AiGJotL6KXLX6bAS6R2BW7cJ7mcmtSq+HxpyTuHIhHboYzahF5OM8qO4eWy
    PFFCOZ5WPGL7lpChtYRx3JisHKiK5rFDof3XadxHKjgSH4+U3JjTiflMr4ivD+D/
    POTi4//d/vSJw4Oqao5VxZ2vo+F04pBnncNJ0wJEXaOfUjsk7yShuWEsd5dG7ldG
    IYjbPl68GhImB5XShuoF4AmVds+BWSgz2bTi2056k1CK2oyWs8IIhAdrUWJ+8FsB
    cmCk33q9pEdcAte/5LgtW8RN0pz0dlRADvhUQYRlTu/ocwdxoBNxkE8hJA9I1cxs
    Hlx/7YbfbKlP2WdFQcX2TOkBeBEK+Q3fYhz0fIw4xSA4/xSeWGhKCtt1Fd1H8Dyw
    FPzy4Qbg93vf1Ha4LEY=
    -----END CERTIFICATE-----
    
