---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUIFf3WEVlnS/Z4HNqBKT3Z0CJ3EowDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI4MDkyNTAwWhcNMjQwODI2MDkyNTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AM0CFqJN4n56ucnuZt1KCkL9OzPBr6xmq7r4bKrgL849VCDgGDfmTmCfhh3IOWXe
    jEKb+bCaP1K9MMUPWbz2ajmihICUHQ+LQn/oyk6PH7EgViba+2gjDkmRCeXerDZx
    252U9qaeecc5kUMWotQ1wiwv1tF7rKo6zRN0QP7EAF/pdTX6QrzWwyHQ6sZHVFy0
    jOKJlXKWQpmwMxuVcEAYXQ86f4CrfqArp65JHM7hf2ICAoJ4ZxvIOGfikwm0QrVX
    t7Ad1TAYXheAqY/m+RTtn51Zbo9J25Zu+uKRi8QpYZCSP1sQWBrJrsLXr2ykXhwA
    QNT86m2FKljB/Mv22JNhu59bnc/XyltIR8RfuRomohz1afrRApcOGNeW07chHqCv
    mCRRt0gwVJPd1zOOv9v14XfLiI/TqwgAHq+33s82ClxZeKvBlJm6w21ylsFU6mMZ
    DG2buV9XeIIHMNmeM+vW11OdGD4Rir55nT68TnCnNaflPxFtmIGJPA4+hNXqLemt
    LcmAuYE8oNSblxMIElc04wo8hIp3Il7F5EgJQgKUl6fnoszAUlHzuDEWeVr+Hgle
    OCiDA4a4LfFSS3q9OONkCfBMFJjjZK+dDCt191iJVZzs+U2lgLT7UA+CKfZNWlV9
    1p1gNz146mFpFUV9XfWIamLQGe1J9Di5CImThuZsb5+3AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBThm0mTJCuaFt1Y
    RZkn18j1exDtGTANBgkqhkiG9w0BAQ0FAAOCAgEAncEQGjzj53y+NEIXtGSY6Lkk
    AqOStQdZfXc+idsW3v6xxNHqt4/mv8MBWPuJl6DDtmjB+1BqhAWlci3cOjjN//aV
    ddSF/rEkbM/kT/7pFyw8X290ydMHVeZuVvjKi33AscMnQJQ24ESCmqqaH6QBxbjl
    tbrclMiBDGoNLC4Njqg4WP5icyU3+2h2F4M7kiGZpASKQG/kD4+6fyaM/5aWHlGY
    kKJc4XMWpbX0m4qzjfM0Bdt1hY9Z9IkPZjG308w5VZh22qOH6qRTy8cri9drNn4W
    hohCcucR2cG5FCfR/vR0qmmX9VTbVDddjnoeY3EVhK0ZfGvx+2dF54F6IR/9tLh8
    RYedUL2B5MRUm93Cl3XGEZ+QuUJNJg/fWcIOuRaC2hUsds5IiORhZa37nvIuOLCQ
    1i3qnhPareBUlAvbaMOtoQBAURb9nD3xSMCMNPchDR0jrTOZaLaXKNpTuKY8NzEk
    ewqxeZV9wXlIij2RlPtg/o6+4ewiJTXVfHPQbKjpM7x4JfeN36nBDLk3L7Gb9Xe4
    eRlNe+8X/Z/++uhcmE/RpzZGpOk+t5LUjrjWig/UXyoxTKbMugeGYZ/I/K9nlsc0
    2PnpQ0Ij7vO5LZ3iFGFfVYm8Xj9YKuFc0QH6TgRuB0+9QHBRAcVQSpFWYugHhFYZ
    ZoPwR0XQuUYOB77lwCk=
    -----END CERTIFICATE-----
    
