---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUPnu4VfA6p4aCre3rX5qa5bjGFP8wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI3MDkxNzAwWhcNMjQwODI1MDkxNzAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AM5PBqiMUnKm7Sg0wZHZtautwPWrgOeSHy4soEoBkUNoqokK/GH+Afa+ntxZRdpy
    /zWCxu5eMi+T41uLgjYg8RC+3H6UUcufTLIAG/P72GJXBkRhiZibBELZlGbcZw4d
    G2gATe1B89qlSB2Mv81uNaHukEVGfrVL51B1bLXElykeNoHBDVa+jF5QfXxsUpqb
    6r5+FreexVfmnYFF6nuVd8uVFL4PgXJj9fJTEEFS1r6RuEMV0yvSpncbQNq9c54r
    8U2Y8HUoTzueMLJPeF1bxSmlYJUMetDvV0hzm2JILfcg2rcnL8FiT4LVXuXj333t
    uYPOEzsu4Rofreie4Bsr5dN3faNYGmIWd5LNVcdonLa1FhY0TxFBiKRSaUq7n7fL
    F/nRSYhborbsUBJZvJYBoRSPPSX+It2/LF8I6WxRQHzTIqXsGWNV/Cg9iVMwOFIM
    +cNtL4HQPRgnK6AClTnvXgUB3jnLH6ObFeAXp83VGxpmMnUWwY44kavaB6l6IgN3
    5AGqAYbszhYXrlzAg4ipDgw/eIyXXkdBIzvZwS1Ie1pO9z6O/qaJ+Uf4DhU3TfrT
    mtNDqrvBo/VyCe5Rpy4px/JX7gcRu9FdYj025+7NMW81RT8ztEInVHsOC6uXWVSv
    3dsPLESvHBrjafavPpFQRFOY/yyoLpvQ4lKklUprzUW5AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQiuUoi47yyo5Z9
    3eVQqdpn6TxM4zANBgkqhkiG9w0BAQ0FAAOCAgEAqwYZmmkkiQcVs0Ms94j/y0w6
    E4QcLUcMOao+c1ho4rCMVLYz+WRrlqXmqfZiEwzDB8J8oZo7TORLm0Lfjcnq74ua
    W3ne3xTawH2ORbLaJfplz/rraiVJdP9l/h0lg/Y+2GigUblXHH6zygFesnZasI/X
    rgc3tINYHj1ywoAFniSMmhFVStHWcdDh0PxVBhu2jvGVBTHYmeJXzTsSmNBfR3p7
    KvevljopVOpQJm5C9IUW+jotbknTfDgdcqtK3Unfv3hfgXN5GRXdBbCTCsrnONSs
    /t7V2NUFoVG28jgchYKlSzAqbl9tOJ42g6ZxF7su+NvZdzkULA3ewSi59WxWBqm5
    9SRr+9mFhUYTbTyrgESOx8wOcN+MP/EXORdBj+XmAO9rDKQjpcUwM+8oJjEHcO7x
    mbCyKz4tUVYidGFQfNiEGWYmQxVeul6kArtZ/vnKpdt8Cm4a/1p+OEOWZCLP4Itc
    PGUJg4r5HNhkadRFRgarJVIxAPd0ht9I9sOSQ5X+RfI1f/ZgeJIpZLnEv0AFjo5V
    0ADCSH5qL8332QGAG9JA16vmwRNTFPOf82j77+8gmWR6E2krXhH7zmtucIfVsQ1F
    mT/9dW/HrSE+JOa4c65m3cOZHPcDSO8VfolaD7EmXzLcHiBgiKvXNHgXxGNKq1Ns
    5gR7r+HFDxv7UqkYXG8=
    -----END CERTIFICATE-----
    
