---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUK+cLiEE6+mo2kVcocpDy/PMH6L0wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI5MDgxMDAwWhcNMjQwODI3MDgxMDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKuBrsLx6wimx8DH6AzKc6ohFgG1ZlAOmLPJQDCEVpCR7XXwCyK1ykzg1r7+Q1JC
    ZHxd5Ji17vsTsCKx2ucFQ7FIoJvX+e3vUmjrKNYBRopNV1m8bEdtLGnP9DLmX56d
    GW+xIsXB8wjYWFpZow5KPwrEsnhPpE5ijsHpOikoMDi+JAnE7G75f45WhrjnHhpB
    dU9ip78v1lc0mu4YokEMr0l+3ZTiu72R+Yiwwpbg8sQO+0GeF5Mpu0ngrWB/8kD1
    WpzgzVYmrFl3b82Vhoq/C6E7mqfJxOSsLsv4W5eKJp72r1M6HPRVLUcQf0qOPbDB
    HwHzeZVhFhXWhWK/+7//IjwOoGRNxeA03cxUaaY5EjXR5nlJNe+MdKNnnnUnaINQ
    xiSQM0dIjHZXCz/xULcLzAEx9pJrVd5rl1jLyfxYsHgJUmYNvigfL/+QRaPnCh7f
    K0SU2y081lG5fS+7ppWbd3zFKdKU5h1lfHCfJJy49dycJW3gMZHvyOFYPcljQMUE
    Gp02CtdTyl2zQJ3WCdIFTXzMU5EhnSmvIIybjcAXCyEuFpoq/LmKN1xjpl/JE1//
    o5QQ1r8vBmM5dNx6COtfIh+KgBSjtd3WrMy+Bo3kslafEO/fVNdtzO7pYlXLFMej
    D0+wNoJXv2/RgMVp2zTOt6ShwMNve2OrBpUy2LmBe9kvAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRPJ8IZxaUmn0s9
    OhLB0L6Cph5xnjANBgkqhkiG9w0BAQ0FAAOCAgEAO3l6t9YJznz41LaIzO1HvUzL
    qVHxObHM1QgWkGu9rff6KDVtkhs9rZAqwgS1dm6FfrEa/bn8dANAqap4SbGG76eN
    eWDnGSrN4DPV+cK8e+oRjKVHEZRl/UzkcXpFjnAGd/jbjN4gIAxa5uDjbBY2lpXO
    2u7Rxr5PhJDJqBtIGL8lV0CEQOcEenpdtVYhTFDKu49cHjcWqz4+c1bfXQXMtJGl
    9SiC4ucZ2N8+CIFN7G5l6JVtT4TyISu5QX7ujHecZR3azRMFUurCRHhVEM7WTmBH
    BGhu6PYEoyxIe7zzkbV/uOE8IrE1Aj7RtPZmo/VowbjRx5hz8h1xItRLf4Oyt2Tg
    NLZs4k/V1d3sfmramNPQ1U5Me4QmzGFElagfyJqDmtFkLqCdGv8CmZP04EZcQRGg
    fQStlp8hzWAtKZptXUjajHRfp8MuhDGU0qoiNZry/hpb0gjvWypWNIRCCOq+IMvv
    W2lJxTEru4jcjGagREBTw8tmnCyfpsQmuThkHMozr55vSftTqey7bNyl4VBKQgX4
    G6a/sR1+bKADpWXuX/25NCuExDE8UaHReXP/HM/7EiHA2kSdop8M/E7KeN4BxUlP
    12di5FcuVfP5xeS7dpIJzOlBBfzK4KqhOloR0rO/dJZs1f1UlIeP48rSXlBjiz92
    sOEVr43L7Bw0zDET/xk=
    -----END CERTIFICATE-----
    
