---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUJFmt2JaGXUwd7s2bRB0+dOQ5Q9AwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODMwMDkxNzAwWhcNMjQwODI4MDkxNzAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOIPD0VZHWl6mbUBOwqbj3xXqncRzl+v9piTW7Ok5qY+/VVnyEw7Zh0BOAUZhCrb
    P+tuv/bc7NAAfBXVg4ge3BDjv6HwnZpSnDEoH7YJ/5bYG/CItufpQkxvRkuiat0P
    vEYmZ3gRJkxedtn3wBLQaPKaHwehh/HI17BcLVKAxpSsYg+JvntoTDw8Ulf0rcdO
    8Ectm+gqXFyvSGR+STGGMNZUo33IWEgVSi7fnpd/4LU/MoWWV/z4LfuGRGzKQBAT
    mZagvnCBGsk3E++LGbauDEDv/1chsm+csRqVymdJLQy5/9ltbRRt1N54HwTVwVkG
    onIVW3Lsrwl0eBizzsVW1S1pyUKzorJxOLR4eSZE7KaxlSHWX0wffmIGQMbzsJng
    HCDUoDWIw0l3Lk9oI4Pl4tzHCK/gyHqQP9A+TKAlKG9vA06toigQkFK2nxxObji3
    XpOqQ2Kh9woe8cLhTovgFB3ZSL4HN5MnG1EojF0XoU3OkyUdYFqJuQtgPQSGjrmY
    c2y+lqM41V6bIl9Xdd9fIeot0Fl2L7kk1INM3ss8PlXun3kJi5F+0R9qhNJ1hm68
    g0hR+TeWykO+gjtvc4bHTINIOLzQumq/eL/62zI7pRFcn3E5JokZ38Ke2Z5O4O8S
    wfSy8RnyaBraKXJ24PTd131xdZWfiJns8ixhLeB7XisJAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRlhRUs+HVaGTXU
    ZGK0ldSQvqxTgjANBgkqhkiG9w0BAQ0FAAOCAgEAhJcvK0v8367YD2kJ6jJ6VgpJ
    TlGYRIHZKDf1C92/H4ZRgzcBoIUXXA2pSjQECOwietv2SWuuiziArjGhxy2eiQha
    kyrIv6ZsA3F/c/+84zeyUb9/hjbU5Ha0VZ30/BPHJSXQH5hyWiFKIR6B9uZ3yvDl
    YR3cQOwfwqEdMsQhaEUoaM3gqP+iBMBz1W+sH5LFJkbybuyqQOOmz9uQ7K/rB9Bf
    ypB+0+KpuGXnUARCR/FNFOO9HiCOtu0Z4kpWgSJDzZUTLX6xuyete6ufxz2c5YY+
    nou6HmT5NiU2Y6JYvu4nWb4Ad1alINvLebOBJiKKbYRm3lF0NlVoA5AgX4mwTrdn
    66dQdBRzVdfi52jzakfxAjloMPDCh0ITucFM9YEHGYqzxJLZz+5ge1PUx99z5OCV
    svqhExx/LSBz0o4Hkg+GZY8ZEioLiW71upf58JbUWUssFv95w/xrBPnz92DaVENC
    YXk9D+8IW752t4PM117LDEI8O4zGLIbtz5IL6JiWTVw7JfxRuK2/2q8KKfvdMJrl
    DKVXDdayeENVD21nQPhluhTE2jyXU5L1Lpezrx/fVrl/FfMYxaYRI1b24vABCR6B
    tBZyG/SyCiY5I2pmAcCafC5H3zZEDZ9KPMVzqbxCgcDObt7jBFcBo1KDfQ+b6rRO
    c2cUiB7cM/KyXRfsS40=
    -----END CERTIFICATE-----
    
