---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUJhb+7lHYX2n0Lt6NvaJaCe9CfrIwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMDMxMDk0MzAwWhcNMjQxMDI5MDk0MzAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    APFSPEVbH46jt4854d3lPzvW4mVf6WjZH7OD95o1sIzJ42zpYAiLaOs9U+97aN6d
    zvbdQlKjkq6HjjlTol8XbFXvAxbjFDCm38AayywLqcOuvhZaOM3B0lCwOxwHa35B
    xtA7maldWNntzeIIGsRKWwRbcElSoMkqt1ZFn18dN0PvEoqzQwtj2z7s01AS6M4f
    eS9C+kIA4UWovceaYnLcM2hNkfG4SLXiuaraLeK/nE1RVmlS0W7O6RnZnrNhrlCo
    LdZ+qGBRphvP+By7bSejy/DJtkGD2vsdYec7GHurqGbL+fyU2XXJuEwjWuLoaRrV
    ub/bSsGYYVfFSUR6BogXDFeg1WnXQ1qOjH64MiVUDy9DsYbQOh1JxXYyCAT6XK4e
    Nvin+WscZZ+Ag2rSHecMSaPB7K+FI44SdBPqWwbCZbZ9NoqRCclCF9uDU03zqUDn
    YxXoBd1E4DaFUbt2EMNBS6nMSCdOqCCUGTZsU57Y8RsxpQ2TcjlC3WTB1uZBioGa
    ZYpmkbVVDSZoTyZM4ttXVQ/txQA4exSxa1tJdqGzmtKcsZX3r0wdmt9DGPDj1wHo
    jjWSkBU7FcuAEGRgCcQVaCa88CBcxSwEDgjQLL+5GlYwr6kNmW6sCN3Ii82aYOPj
    2LxoYk/P6gUZOZgoOW92IPfF8FSF6YZck/NzeQNjfezxAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ2ZElBv+NQMeg7
    r7Te+yDJzEeXBTANBgkqhkiG9w0BAQ0FAAOCAgEArqM/XFy7Kl48fabe8esF7MIq
    aVkYLicdP0mq90knnYflk/VkJ/JwEMQ88K7yczozqhSzBaNwpPREBSTs/AYJr0ZL
    MVjX3xAsCfea3gUY2uLf+J7MDfl2GCYD2QMbj4hHk/C7c+XwSVT8YDyMPX81JiQD
    XDj4+pXjwccnwd4zQjLW128Ws/VoNVILrtd2tZFTTf5n4nKQQdlzYwrfauly0Hck
    rR4viRJ0h2BAaoQo82Eu4/uffyNNLljU+2AV4tJjiiOIuiIaSIB5jaodFK2Hl5oG
    1GTdjmeAiNC0GDyL7RNf7liKJyegq/L/gYEPNOGCVePmTiHkhdqx0+xBQM0QhwVN
    ExYQ9bR0pf775J5v1r2cl/RqSiYT2NbuPocE0OMP87OBFNyv1LLCgjLeCDAzMrTN
    UlmbZp/LADidqM21egnFfilWCTSHhenNRjpK/lSSmOWC5/m+aZxU9sNopFAnXNT2
    aQd7pbdjxCKbqr2UwEBy+yogejIX4hbnzVu24626kxOB9lYeIOPiyLeeJPVW/oIF
    70lVLxHRI8KtresMg4tohNY/Sg0NKSV4XJDtSs529vnHhot/Lg0ZljfAFGkaa6Pr
    MfwLvg/dQbKyeLUbEHjCHkBqiMYgCCP9WTxdYRJJIsvcrTA4wA6+T8M3RJy/1GaG
    zlVK9x1hyn17qwL7o/k=
    -----END CERTIFICATE-----
    
