---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUXIXF3x1ZFLjB53GGfZETq/LH+VYwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMjEwMDkzOTAwWhcNMjQxMjA4MDkzOTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANCNNAt1Hyvz64QF/zJL/EaIjOMGmmPUXEVHMILWRqy1/SaXD/o0UtMgFg2Psr8k
    48vCUitLmvub2hzudXwr7guvQ8ZAYvA+oCNzPue5SEjRLpCECzYRuk50R7DvcF9V
    PtlAIwcL+vPr2c4M0qvVmcyvAGwOfkTUbHXhUBRJ9qtzAPaKrcA49Gq7J0YqxsSM
    apKINX0CG/8dFVc/ouL2NVqAPYp2NLzZovJkxOmHsQv1+0S67N4cDliaLvT4DzLw
    ZwwPtWMmoeMXBpyy4SE9WJm8nXMde3lTSlpHuj8wzOoxt4abZb74Dp63draKQ8g3
    jDbdqjb6CCjWSjlXmm7IXNFyylf1sLyysGfo0awCVckPvjJpO2QtxTENyHTS54eX
    xehmplxfG99iddhZ8P9Ou4BLXzlYjR3/KOcfkoV3edKNcS7qqS3uMDClkTbFhAlK
    rrr+1DoXs7/Uff3tWqnnNG88pWhJzq5c7DQXq6YEfS7g2MPC6rcXrTDq9lhdYY1S
    OgCLaPYa1jP2GzmIOcEPkqtZOhsg4ai6w+6QtMcecsCuCfqeMk44BmenW8Xe3aSA
    zLfxhQljTr5X4W6CM+8hzbZtaO0H4Js1dkKUok7i20ySWEvzCHWa3/wF5+zX/jud
    8SUGtCPAGIWoQMCr3xGeDXVzERBR0nX8srl6dfNzwHEnAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQVElhkl4mFjLT3
    CZz1nHC3WOfM3TANBgkqhkiG9w0BAQ0FAAOCAgEAmSwHRVeUrUU4XCiZcIgcP5Y0
    jyVAqsBa1m57MSSlua9ogSoTY7RlmdJ/c1TkN5fx95RX4GTcbaGrfw4FDdIV3cVk
    IT6APseK/xKoZb3fTkW26MpD+w5/LXJX4U3rjICWsDUg97K8Dkxl4iVhe68qA/QU
    7IBrWClKbhri1c2vcfr+lAJiAWTowmQlEBXUpkR7TQ3L9NIHdhXrhNPsDJuQ1GAK
    XjN75Ea1NO9veABKVPNC3/4Kukvp1bEaNBf+ARavzmQgHWp8KUL0zKn1HIt00Vsg
    lKNDaNmIneY+ojNdlCJK17ctJNzBhNJkvcETKy6/soztIuc5FwUTFWof0EV0JmQV
    PnIAH9H/a3zH3VyvL8FKflcyCkNeTB5JxaUwu5iLIdBzmBt9EUOst+UgqAExbpy2
    HFYWvF1q2oHUp5866XPPns1qrR9oX5kFdZydemJJj6UjoGCZASwNCgKp7dRpHgeV
    oADgipLrMP9IhY+w1O+VjyCxtB50+Ar+helgUprMsJ2zImNJU6/ZmP+DdgdBKPFN
    razlIM70nRp5VXRJh8Hoxu+LANvZMwimCl60+VvU8jXPsD0TUhv27axgy10Ovb/B
    +gQqRWkcL1u04L3nFUNZEqZLKKU4iRKL3ruA1PGHCTkIk0nKwen2iQonNyH5BHV5
    NkZHM8iF87Hl99e1nYY=
    -----END CERTIFICATE-----
    
