---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUXAqskGTZCovipE02FjFm7fPpZ4gwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwOTA0MDk1MTAwWhcNMjQwOTAyMDk1MTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AM8gf+eIXTgRAofXxIh1hsGtXj4oYDuFXHlix/8N5gLtJ2ASp18ZVpb/GtykQjPj
    bOZjqj7BlxfELW53YnCsGs7ZvywwSk/qeW5oOn7yEYwLuxLeDe8uMMLGopdyYEAt
    yDlZBFdARNuGbJSHijiKxL9Ac/U4hWzXjAPm9/Htlz9fiTxQUjCNXjVuuFS5XJ0M
    uj6+QkfXO9YQQ0VJQgV6TnzzSRB9lWrlApB0Qx124dbP1stMnL/EXMOHkI79ye13
    00rQGTQjBrOUYKxwPYVWpGwZOIBQkTc+tXvNz2vHx1dkmg/wW+J52hHvpZnl75BV
    RbGbHlp1qo6AHo6BxomOaIytpEVem2spENoGWcl41jRHqtVjwR4G9/ePc/jna0WK
    mdd8SSMUEaeMBLMlbOoVm6WTbOJE2KtVgHlH1m7fesvIYy67YDThFxfCYutYVmcy
    i5A2A4q+aLAMLFntSjDyhbhdohoKd5feBDfPwhX4/K1RmZUxpRQs/MCYKpYaLuXE
    LB397xEToSSdSlplACzvjPqFAHIj7Uv/YcOBCOA6bFt8S2t/3shbUaEUtFrvu1po
    jWbpT9mR7qdKgW4PSyIHy73jAH8rG3IjE3hJ233UmKWYZmvC1mZ/HxrCum+GTvcA
    A+KFQBYu8w77meJioTcRp9Uog6AsG4WFgH7Ji0CWM297AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR0QUCwqSy/Apu7
    ILw5REU4lPhNjDANBgkqhkiG9w0BAQ0FAAOCAgEAEbalXNNeHIXf+OCmFr04aR5v
    xJhm1Akp+V3vV93VWG7UQTwlhAgLwlW6/cIzqUFMuEuq6mQF04asA85RDRsm4Iwq
    EyHF0MVt8foUsvxRl/YJ/Scwb3iVHAKGVbsdBywR52Wg6nHJlIGFtdi05muS/T34
    alc9LMTx94DEVhXnqm16fAyWzaF4lKdgf+NIaB30OSFBGlrJizPVSDDh7GAne9h7
    bw1VKNb3R+0xhKpJSFbv6IiwiWAHGaNmtrKkmS/Fs090gTdyf/1rkX721fL4WABn
    p6WqrL/LjwJag+DFIHRu2vUAWVIDEvp/MRvoG4RcOeFkSqHIVLsAWryldccf2qi9
    MWaICQoaDXL5ZMfH3HFHfynVJ/MzkRfKog3iUZdONUjBdN47BJnXVuBStZ3QIeub
    dBK5afeu0iPYnZJkHSKV0/FoTUmR+tgoeMJGwSKpPPkPfB2aiYeHmaowB9qhD3Dl
    2iJeHkTAw3HTlBAEZdeqISAPHKNHqdKvjFZy5QC6rbKyKBPEHUhvy5ArF6tAL9NB
    HfUCISRxqBsbl600VTgqEoQnL3xNWg1/0Z5+3YPPLplZt4WfUE6Lrlj+9Fu4DqVO
    kh9R5h9ThcMJcg+0eDfKpJDvK7NEfLB28Iyua2EnZmrtQFRdASudVOH3dl2w6F7+
    Mhi52m8LFbAdHt+bDo4=
    -----END CERTIFICATE-----
    
