---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUAXyeucuvb+z6Jh9qWQiFWEDXSf4wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI4MTM0MTAwWhcNMjQwODI2MTM0MTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOCSy3WGB740I3W95GlxtbWqEhp8oPCOv1dUYr+YVeWZ/ySzhCNsJphwSzTZwiqW
    F/CYMOMTKP1KGPHCoO7zsJiL6GiDMZ3YOw+Do7eiWqPSYd12bnhBh/so6vt/mvMY
    oqQuHHYs0YJps6JXu8lYLRRcivSupue+61lHcI8425RHcFH3vzC55rRWsjZh6sZx
    YPIfkzv1vpjWQp5bGRR9X/mYnNIolO8aOL2vKUzmHLkiQXb34jWQ0PbeWQ2Fo3nD
    T4cWk9b8/2MzyRpftlfWHzdlv3HK/HmuRg+rJwFw7GTn4T58uwyqaIG1ds/HPI83
    ca6rO8EQr3vBEoe9ICbmVRTO/aJPtUyb+IFqe7WdK5yuy1ayzHAFOem3jPd0cYkY
    ghgKroLv6DwE6mK2RjO/rqeZXnPajImDlV4R0fnyVZuvK8p4f+EEzzBtSxPRw3NM
    WwvOYLd1gEl02JGh2cDZzKTy28rdJPLDnxjymCx3SBqWmeOzbTjpJTpGdCxIhCjr
    fqmllzqp2Iu6w0z3e5Z7dXUoVBYd3hkTeDuaKrnbEMmTRaxB5wvWmmEbLq00IzAg
    wNKeY/0g8AO58GD9FtFLmiRfFISWJKUhjqiL2F2wfA6QZKdTlHpZ9DzWH0BOBCCf
    C00yDMHXVrFlFvd9xKHn8Jmp3BJfS+8hHWC+HtXrchU7AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT8X1WQbwpUDuUi
    pnRvatNc76dyfDANBgkqhkiG9w0BAQ0FAAOCAgEACiID1I6wzL6oB9OMJzE4rlDX
    c9thWnuRf53Y1xYjHGIm++u/cXXQzGxOHbosfow7RcVYJu8ExPKVMp/5gMCSmObt
    ptfLOUAX5P2odiu4kDcpdDCGyh9AY5PEf44/14S4Z4ZO/quuekgGKT3IHkQOsOr5
    3vMaCcL1mXPFH1lGYo1exLSMPsec7FJSMaQsKKSwCMpgMQ5BWCNsvj20Lo97RVZn
    apX2f9IgHWXLXDb0jGAog105Hvyj9obieM5w2a5RQ9z7+S5sGNTG8DFFBnLzHQY8
    nZjMTFZh1FdGztRBM0mnJO5WSN2EBThastzsIkMWwcAZUJkyWDyuZIwLyFX/if93
    fOZE7M4TkgbTM2PkW9f/lbZKEjUwXM8xQA6fL9z/p+dBtfpJfI8GPOXK7IIrRvDu
    3ikIB+f2he/+VJaE8TFF0hHy1lzah0WNt7bOqFJG6gvcQTgDe4ZTIE/zi7XxSoHg
    t0KvdI2RZ/vGQ+FemtYB7aZlD0TdraBLyCLYm10ACb/cmxucFO8WUb6wYDsLH47o
    B9Mnn6tI8ihpdjeSuHGHOpLTsLJIGH0NqbDEqLYywPlCYdAyVLe1DrqEn08jURNh
    Gkd9jLmr0ZiG87IErTabtULJvaae3GkItNHkQfgC/WUCuk7GymwnKQoLMp6ujSjG
    2ZlKhOjGSNKouO0HRjI=
    -----END CERTIFICATE-----
    
