---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUV2N3E68Q9LHDIxfWSfsrGONJVZ8wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODI3MTAyNDAwWhcNMjQwODI1MTAyNDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANaVEbfbDWTofO63sbTLGcN2XBHH3dEXV57+xSF9OpHgBpo5jXlceKhDxL/Nsx/p
    pw4LmO7mf6fUGE8B+nVE+aDImGq3Dbf7EUb3cmAZBurPQw5crk3UuUhzhgIvnmiT
    L+PezxiJO/lXw6K/6HiYIik4p9BOM5nzkpT4iRhOkB8a6Vwvy8xOSogB9CBRerR2
    /j+iJO6qR6IusRR7sRNlOndvzWMKgsGTzKlONK0lDXj9pEjHdBcLut5pxE5dGz1d
    CWyb9JF78d5Zux/QYTsxeOlxEDBfgaaYC2PDl/MIQpBlDRiQMd2JGz9HpIqf5OTv
    7J3JN3PjGXpZkaph6Cr4iVpyPuuZA6CK1VvyIZ86cG8aEdBAt9P8X1Vuq2fgXnyF
    5PcH+h8CGUBeA0ZcJ4I9WIfny1dBZnE3JD/2l3Bgb81JBUxgsC4etorB7wJbJrr1
    DyFhYPZ8AIbSsrC4McNy7x20dTG1wItfS+PrmB9wjwSwI/2Fm4SMi6bLj8Y1NQAP
    HgFxHZtAmSZwCZIHTHHd3kWO0ise0+n+eI6TgaQ/Y7Lh10p7aSOy7HdsE3hHnN2I
    JIzJfOLWNrEo6ur3YteCGM5GgnnNzM6p3D6p15db7HN5lawiq1hl6t5/uuCX7piu
    ukDHa8pWEr3qOc/xE07okUqzD+JxLSTwojlkn5h/5gGDAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQO5nUIbrnAHgWr
    mn9peZSk862aNzANBgkqhkiG9w0BAQ0FAAOCAgEAY/Bmm8QJyLqgyt1ArRQPCUyZ
    /BQgN5JlEuA5Iv+jeRQRhGuXif9wwCncPQRqcmUqo5kP6yD9SEeCWftQWq77+Tre
    HKRXm9opL5HwdnR0Y+HudSSB22k6VcHUFbtHBqy9pqTvrVAdmBFzetP8/3iqlP3q
    XdehdAVHzovCmPiDiIH6pFetcWnpqf5ppJo/J1fqIaMt68PivbSFjnihmdOLL+7b
    4ivt8221bibMmN1M0mO4BfWo6yXM2u2USsbU9RSo006xaCuRyJpq0z92uhQGy6uo
    a7LRFUVBk1m4fj710f+wLMV+RSzX8w/g0jIS2xtHwFBrNAinB72OOQUb7E1EgyaS
    fhYtzP8T4cZZIN5YOu5M4rJ0xMyN32qvIeD9oBT2xqx8N4g5wn1URCx9AfHt3e8Q
    fUyccgRyuKgaQKk449QWxT9QuIqVnOgkmR3M/OOEKhwEg8HPNGZ0oTatvnfvLAMf
    EjMkeiOM2cHpBCjdAKhPoKlU2jntgmudYhXuHC16hAwDjEk/imV/qMYtK/YxVNIJ
    iddi4+P5oZ/Uec4lI3e0jFvg3p5mhJWfO4+3KLB2+zbRVNz1sdyYEIN4MU8WR9q9
    AU6ZI++N4sFHYE6K89DYaQh8pYGU4C+nWYxjs9uSDdZyd/U0UPBqBMG46L+Vje1q
    vvy7rS/N/sptkF34UXI=
    -----END CERTIFICATE-----
    
